// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR8QL3wt6nxrpxeJziyySG8YElFf0sD7Q',
    appId: '1:195081687950:web:29cd986008b916ed97cadf',
    messagingSenderId: '195081687950',
    projectId: 'dits-70857',
    authDomain: 'dits-70857.firebaseapp.com',
    storageBucket: 'dits-70857.appspot.com',
    measurementId: 'G-NNTN8Z5LXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA547ZxV9wKbXeQodUhOlUKYnXo7jjPewc',
    appId: '1:195081687950:android:5e85645eabba402e97cadf',
    messagingSenderId: '195081687950',
    projectId: 'dits-70857',
    storageBucket: 'dits-70857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7sT2fz5fyyTqgALQk6gq3DP3xA3_lNM',
    appId: '1:195081687950:ios:477fb87735d0026f97cadf',
    messagingSenderId: '195081687950',
    projectId: 'dits-70857',
    storageBucket: 'dits-70857.appspot.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7sT2fz5fyyTqgALQk6gq3DP3xA3_lNM',
    appId: '1:195081687950:ios:477fb87735d0026f97cadf',
    messagingSenderId: '195081687950',
    projectId: 'dits-70857',
    storageBucket: 'dits-70857.appspot.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR8QL3wt6nxrpxeJziyySG8YElFf0sD7Q',
    appId: '1:195081687950:web:47ab6655522bd22f97cadf',
    messagingSenderId: '195081687950',
    projectId: 'dits-70857',
    authDomain: 'dits-70857.firebaseapp.com',
    storageBucket: 'dits-70857.appspot.com',
    measurementId: 'G-Q4V48HW8TT',
  );
}
